---
all:
  children:
    dcs:
    db:

dcs:
  hosts:
    consul01:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_private_key_file: .vagrant/machines/consul01/virtualbox/private_key
    consul02:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_ssh_private_key_file: .vagrant/machines/consul02/virtualbox/private_key
    consul03:
      ansible_host: 127.0.0.1
      ansible_port: 2201
      ansible_ssh_private_key_file: .vagrant/machines/consul03/virtualbox/private_key

db:
  hosts:
    pg01:
      ansible_host: 127.0.0.1
      ansible_port: 2202
      ansible_ssh_private_key_file: .vagrant/machines/pg01/virtualbox/private_key
    pg02:
      ansible_host: 127.0.0.1
      ansible_port: 2203
      ansible_ssh_private_key_file: .vagrant/machines/pg02/virtualbox/private_key